# Generated by Django 4.1 on 2022-11-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('patent', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('car_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
