# Generated by Django 4.1 on 2023-04-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('job', models.CharField(max_length=100)),
                ('start_contract', models.DateField()),
                ('end_contract', models.DateField()),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.costcenter')),
            ],
        ),
        migrations.CreateModel(
            name='MiningDocumentTypeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documenttype')),
                ('mining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mining')),
            ],
        ),
    ]
