# Generated by Django 4.1 on 2022-12-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
