# Generated by Django 4.1 on 2022-12-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
