# Generated by Django 4.1 on 2023-02-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mining',
        ),
    ]
