# Generated by Django 4.1 on 2022-12-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='expired',
            new_name='has_expired',
        ),
    ]
