# Generated by Django 4.1 on 2022-12-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_documentcar_delete_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentCar',
            new_name='CarDocument',
        ),
    ]
