# Generated by Django 4.1 on 2023-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contracttype_worker_miningdocumenttyperequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='end_contract',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='start_contract',
            field=models.DateField(blank=True),
        ),
    ]
