# Generated by Django 4.1 on 2023-04-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_worker_birthdate_alter_worker_end_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='end_contract',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='start_contract',
            field=models.DateField(blank=True, null=True),
        ),
    ]
