# Generated by Django 4.1 on 2022-12-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_documentcar_cardocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
