# Generated by Django 4.1 on 2023-01-30 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_expired_document_has_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='mining',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.costcenter'),
        ),
    ]
